---
# Retrieve settings file for maven build.
- file:
    path: ~/.m2/
    state: directory
    mode: 0755

- stat: path=~/.m2/settings.xml
  register: settings_exists

#- debug:
#    msg: "{{ settings_exists }}"

#- file: path=DOWNLOAD_DIR_HERE state=directory mode=0755
- stat: path=~/"{{ AGENT_NAME }}".jar
  register: bamboo_jar_exists

#- debug:
#    msg: "{{ bamboo_jar_exists }}"

- get_url:
    url: https://"{{ ATLASSIAN_USER }}":"{{ ATLASSIAN_PASS }}"@"{{ BAMBOO_URL }}""{{ AGENT_NAME }}".jar
    dest: ~/"{{ AGENT_NAME }}".jar
    validate_certs: no
  when: bamboo_jar_exists.stat.exists == false

- shell: java -jar ~/"{{ AGENT_NAME }}".jar https://"{{ BAMBOO_URL }}" status
  register: agent_status
  ignore_errors: yes

#- debug:
#    msg: "{{ agent_status }}"

- shell: java -jar ~/"{{ AGENT_NAME }}".jar https://"{{ BAMBOO_URL }}" install -t "{{ BAMBOO_SHA }}"
  when: bamboo_jar_exists.stat.exists == false

# Copy bamboo capabilities properties file.
- copy:
    src: bamboo-capabilities.properties
    dest: ~/bamboo-agent-home/bin/bamboo-capabilities.properties
    mode: 0644
#  when: bamboo_jar_exists.stat.exists == false

- shell: java -jar ~/"{{ AGENT_NAME }}".jar https://"{{ BAMBOO_URL }}" stop

- shell: java -jar ~/"{{ AGENT_NAME }}".jar https://"{{ BAMBOO_URL }}" start -t "{{ BAMBOO_SHA }}"
